(dp1
S'output'
p2
S"<class 'sqlite3.OperationalError'> no such column: preco_produtos_lojinha"
p3
sS'layer'
p4
S'/home/python/web2pyLojinha/applications/lojinha/controllers/home.py'
p5
sS'code'
p6
S'def index():\n    """\n    example action using the internationalization operator T and flash\n    rendered by views/default/index.html or views/generic.html\n\n    if you need a simple wiki simply replace the two lines below with:\n    return auth.wiki()\n      """       \n    if session.auth:\n        x = session.auth.user\n        y = SQLFORM.grid(db.auth_user,user_signature=False)\n        z = db(db.produtos.id==241).select(\'preco_produtos_lojinha\')\n\n    else:\n        x = "nao ta logado"    \n    return locals()\n\n#===== CRUD ========\n#insert\ndef inserir():\n\treturn dict(form=crud.create(db.books))\n#update\ndef alterar():\n\treturn dict(form=crud.update(db.produtos,request.args(0)))\n#select\ndef listar():\n\treturn dict(form=crud.select(db.books, db.books.id>0)) #db.books.id>0,[\'id\',\'titulo\']\n#delete\ndef deletar():\n\treturn dict(form=crud.delete(db.produtos, request.args(0)))\n#search\ndef buscar():\n\treturn dict(form=crud.search(db.books))\n#=== FIM DO CRUD ===\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/python/web2pyLojinha/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/python/web2pyLojinha/applications/lojinha/controllers/home.py", line 36, in <module>\n  File "/home/python/web2pyLojinha/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/python/web2pyLojinha/applications/lojinha/controllers/home.py", line 12, in index\n    z = db(db.produtos.id==241).select(\'preco_produtos_lojinha\')\n  File "/home/python/web2pyLojinha/gluon/packages/dal/pydal/objects.py", line 2002, in select\n    return adapter.select(self.query,fields,attributes)\n  File "/home/python/web2pyLojinha/gluon/packages/dal/pydal/adapters/sqlite.py", line 122, in select\n    return super(SQLiteAdapter, self).select(query, fields, attributes)\n  File "/home/python/web2pyLojinha/gluon/packages/dal/pydal/adapters/base.py", line 1286, in select\n    return self._select_aux(sql,fields,attributes)\n  File "/home/python/web2pyLojinha/gluon/packages/dal/pydal/adapters/base.py", line 1243, in _select_aux\n    self.execute(sql)\n  File "/home/python/web2pyLojinha/gluon/packages/dal/pydal/adapters/base.py", line 1378, in execute\n    return self.log_execute(*a, **b)\n  File "/home/python/web2pyLojinha/gluon/packages/dal/pydal/adapters/base.py", line 1372, in log_execute\n    ret = self.cursor.execute(command, *a[1:], **b)\nOperationalError: no such column: preco_produtos_lojinha\n'
p11
s.